theme: jekyll-theme-minimal
title: Adrian Q. Silva
description: Full-Stack Web Developer
logo: profile/assets/profile_picture.jpg
linkedIn: https://www.linkedin.com/in/silvadrian3
skills: profile/assets/skill_set.jpg
