theme: jekyll-theme-minimal
name: Adrian Q. Silva
position: Full-Stack Software Engineer
profile_picture: profile/assets/profile_picture.jpg
linkedIn: https://www.linkedin.com/in/silvadrian3
email: silvadrian3@gmail.com
