theme: jekyll-theme-minimal
title: Adrian Q. Silva
description: IT Manager / Senior Full-Stack Web Developer
logo: profile/assets/profile_picture.jpg
linkedIn: https://www.linkedin.com/in/silvadrian3
